copy-left:
  Jordi Boggiano <j.boggiano@seld.be>: JsonFormatter.php
  Konstantin Kudryashiv <ever.zet@gmail.com>: JsonFormatter.php

mapping:
  "Tristan Lins <tristan@lins.io>":
    - "Tristan Lins <tristan.lins@bit3.de>"
  "David Molineus <david.molineus@netzmacht.de>":
    - "David Molineus <mail@netzmacht.de>"
