mapping:
  "Tristan Lins <tristan@lins.io>":
    - Tristan Lins <tristan.lins@bit3.de>
  "David Molineus <david.molineus@netzmacht.de>":
    - David Molineus <mail@netzmacht.de>

copy-left:
  Jordi Boggiano <j.boggiano@seld.be>: JsonFormatter.php
  Konstantin Kudryashiv <ever.zet@gmail.com>: JsonFormatter.php
  Christian Schiffler <c.schiffler@cyberspectrum.de>:
    - PatchingAuthorExtractorTrait.php
    - GitRepository.php
  Tristan Lins <tristan@lins.io>:
    - GitAuthorExtractorTrait.php
    - PatchingAuthorExtractorTrait.php
    - GitRepository.php
  David Molineus <david.molineus@netzmacht.de>:
    - GitRepository.php

exclude:
  - tests/AuthorExtractor/Fixtures
