mapping:
  David Molineus <david.molineus@netzmacht.de>:
    - David Molineus <david.molineus@netzmacht.de>
    - David Molineus <mail@netzmacht.de>

copy-left:
  Jordi Boggiano <j.boggiano@seld.be>: JsonFormatter.php
  Konstantin Kudryashiv <ever.zet@gmail.com>: JsonFormatter.php
