name: PHPCQ author validation

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'PHP: ${{ matrix.php }} Symfony: ${{ matrix.symfony}} Experimental: ${{ matrix.experimental}}'
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '5.6'
            symfony: '^3.0'
            experimental: false
          - php: '7.1'
            symfony: '^3.0'
            experimental: false
          - php: '7.2'
            symfony: '^3.0'
            experimental: false
          - php: '7.3'
            symfony: '^3.0'
            experimental: false
          - php: '7.1'
            symfony: '^4.0'
            experimental: false
          - php: '7.2'
            symfony: '^4.0'
            experimental: false
          - php: '7.3'
            symfony: '^4.0'
            experimental: false
          - php: '7.4'
            symfony: '^4.0'
            experimental: false
          - php: '7.3'
            symfony: '^5.0'
            experimental: false
          - php: '7.4'
            symfony: '^5.0'
            experimental: false


    steps:
      - name: Pull source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # see https://github.com/shivammathur/setup-php
      - name: Setup PHP.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Cache composer cache directory
        uses: actions/cache@v1
        env:
          cache-name: composer-cache-dir
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Cache vendor directory
        uses: actions/cache@v1
        env:
          cache-name: composer-vendor
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.symfony }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-${{ matrix.symfony }}-build-${{ env.cache-name }}-
      - name: Install composer dependencies
        run: |
          composer require symfony/console ${{ matrix.symfony }} --no-update
          composer require symfony/finder ${{ matrix.symfony }} --no-update
          composer require symfony/process ${{ matrix.symfony }} --no-update
          composer require symfony/yaml ${{ matrix.symfony }} --no-update
          composer install

      - name: Run tests
        run: ant -keep-going
